create table address (
    id text not null,
    -- date_created text not null,
    display text not null,
    site_name text,
    building_name text,
    flat_type text,
    flat_number text,
    level_type text,
    level_number text,
    number_first text,
    number_last text,
    lot_number text,
    street_name text not null,
    street_type text,
    street_suffix text,
    locality text not null,
    state text not null,
    postcode text not null,
    -- legal_parcel_id text,
    -- mb_code text,
    -- alias_principal text,
    alias_of text,
    -- primary_secondary text,
    child_of text,
    -- geocode_type text,
    latitude float not null,
    longitude float not null
);

